apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dummy-service
  description: Dummy Service
  tags:
    - java
    - jdk11
    - less
    - more
  annotations:
    github.com/project-slug: wilteus/inventory
spec:
  type: service
  lifecycle: experimental
  owner: platform
  providesApi:
    - dummy-api
  consumesApi:
    - silly
    - namna
